namespace :scraping do
  desc 'Webサイトからギャラリー画像を取得し、DBに保存'
  task save_gallery_data: :environment do
    require 'webdrivers'
    require 'selenium-webdriver'
    require 'nokogiri'

    # Rails 環境のロード
    require File.expand_path('../../../config/environment', __FILE__)

    Webdrivers::Chromedriver.update

    options = Selenium::WebDriver::Chrome::Options.new
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument('--window-size=1280x800')

    driver = Selenium::WebDriver.for(:chrome, options:)

    urls = [
      'https://www.lh-ink.com/photo.php?slide_id=600',
      'https://www.lh-ink.com/photo.php?slide_id=601',
      'https://www.lh-ink.com/photo.php?slide_id=602',
      'https://www.lh-ink.com/photo.php?slide_id=603',
      'https://www.lh-ink.com/photo.php?slide_id=604',
      'https://www.lh-ink.com/photo.php?slide_id=605',
      'https://www.lh-ink.com/photo.php?slide_id=606',
      'https://www.lh-ink.com/photo.php?slide_id=607',
      'https://www.lh-ink.com/photo.php?slide_id=608',
      'https://www.lh-ink.com/photo.php?slide_id=609',
      'https://www.lh-ink.com/photo.php?slide_id=610',
      'https://www.lh-ink.com/photo.php?slide_id=611',
      'https://www.lh-ink.com/photo.php?slide_id=612',
      'https://www.lh-ink.com/photo.php?slide_id=613',
      'https://www.lh-ink.com/photo.php?slide_id=614',
      'https://www.lh-ink.com/photo.php?slide_id=615',
      'https://www.lh-ink.com/photo.php?slide_id=616',
      'https://www.lh-ink.com/photo.php?slide_id=617',
      'https://www.lh-ink.com/photo.php?slide_id=618',
      'https://www.lh-ink.com/photo.php?slide_id=619',
      'https://www.lh-ink.com/photo.php?slide_id=620',
      'https://www.lh-ink.com/photo.php?slide_id=621',
      'https://www.lh-ink.com/photo.php?slide_id=622',
      'https://www.lh-ink.com/photo.php?slide_id=623',
      'https://www.lh-ink.com/photo.php?slide_id=624',
      'https://www.lh-ink.com/photo.php?slide_id=625',
      'https://www.lh-ink.com/photo.php?slide_id=626',
      'https://www.lh-ink.com/photo.php?slide_id=627',
      'https://www.lh-ink.com/photo.php?slide_id=628',
      'https://www.lh-ink.com/photo.php?slide_id=629',
      'https://www.lh-ink.com/photo.php?slide_id=630',
      'https://www.lh-ink.com/photo.php?slide_id=631',
      'https://www.lh-ink.com/photo.php?slide_id=632',
      'https://www.lh-ink.com/photo.php?slide_id=633',
      'https://www.lh-ink.com/photo.php?slide_id=634',
      'https://www.lh-ink.com/photo.php?slide_id=635',
      'https://www.lh-ink.com/photo.php?slide_id=636',
      'https://www.lh-ink.com/photo.php?slide_id=637',
      'https://www.lh-ink.com/photo.php?slide_id=638',
      'https://www.lh-ink.com/photo.php?slide_id=639',
      'https://www.lh-ink.com/photo.php?slide_id=630',
      'https://www.lh-ink.com/photo.php?slide_id=641',
      'https://www.lh-ink.com/photo.php?slide_id=642',
      'https://www.lh-ink.com/photo.php?slide_id=643',
      'https://www.lh-ink.com/photo.php?slide_id=644',
      'https://www.lh-ink.com/photo.php?slide_id=645',
      'https://www.lh-ink.com/photo.php?slide_id=646',
      'https://www.lh-ink.com/photo.php?slide_id=647',
      'https://www.lh-ink.com/photo.php?slide_id=648',
      'https://www.lh-ink.com/photo.php?slide_id=649',
      'https://www.lh-ink.com/photo.php?slide_id=650',
      'https://www.lh-ink.com/photo.php?slide_id=651',
      'https://www.lh-ink.com/photo.php?slide_id=652',
      'https://www.lh-ink.com/photo.php?slide_id=653',
      'https://www.lh-ink.com/photo.php?slide_id=654',
      'https://www.lh-ink.com/photo.php?slide_id=655',
      'https://www.lh-ink.com/photo.php?slide_id=656',
      'https://www.lh-ink.com/photo.php?slide_id=657',
      'https://www.lh-ink.com/photo.php?slide_id=658',
      'https://www.lh-ink.com/photo.php?slide_id=659',
      'https://www.lh-ink.com/photo.php?slide_id=660',
      'https://www.lh-ink.com/photo.php?slide_id=661',
      'https://www.lh-ink.com/photo.php?slide_id=662',
      'https://www.lh-ink.com/photo.php?slide_id=663',
      'https://www.lh-ink.com/photo.php?slide_id=664',
      'https://www.lh-ink.com/photo.php?slide_id=665',
      'https://www.lh-ink.com/photo.php?slide_id=666',
      'https://www.lh-ink.com/photo.php?slide_id=667',
      'https://www.lh-ink.com/photo.php?slide_id=668',
      'https://www.lh-ink.com/photo.php?slide_id=669',
      'https://www.lh-ink.com/photo.php?slide_id=670',
      'https://www.lh-ink.com/photo.php?slide_id=671',
      'https://www.lh-ink.com/photo.php?slide_id=672',
      'https://www.lh-ink.com/photo.php?slide_id=673',
      'https://www.lh-ink.com/photo.php?slide_id=674',
      'https://www.lh-ink.com/photo.php?slide_id=675',
      'https://www.lh-ink.com/photo.php?slide_id=676',
      'https://www.lh-ink.com/photo.php?slide_id=677',
      'https://www.lh-ink.com/photo.php?slide_id=678',
      'https://www.lh-ink.com/photo.php?slide_id=679',
      'https://www.lh-ink.com/photo.php?slide_id=680',
      'https://www.lh-ink.com/photo.php?slide_id=681',
      'https://www.lh-ink.com/photo.php?slide_id=682',
      'https://www.lh-ink.com/photo.php?slide_id=683',
      'https://www.lh-ink.com/photo.php?slide_id=684',
      'https://www.lh-ink.com/photo.php?slide_id=685',
      'https://www.lh-ink.com/photo.php?slide_id=686',
      'https://www.lh-ink.com/photo.php?slide_id=687',
      'https://www.lh-ink.com/photo.php?slide_id=688',
      'https://www.lh-ink.com/photo.php?slide_id=689',
      'https://www.lh-ink.com/photo.php?slide_id=690',
      'https://www.lh-ink.com/photo.php?slide_id=691',
      'https://www.lh-ink.com/photo.php?slide_id=692',
      'https://www.lh-ink.com/photo.php?slide_id=693',
      'https://www.lh-ink.com/photo.php?slide_id=694',
      'https://www.lh-ink.com/photo.php?slide_id=695',
      'https://www.lh-ink.com/photo.php?slide_id=696',
      'https://www.lh-ink.com/photo.php?slide_id=697',
      'https://www.lh-ink.com/photo.php?slide_id=698',
      'https://www.lh-ink.com/photo.php?slide_id=699',
      'https://www.lh-ink.com/photo.php?slide_id=700',
      'https://www.lh-ink.com/photo.php?slide_id=701',
      'https://www.lh-ink.com/photo.php?slide_id=702',
      'https://www.lh-ink.com/photo.php?slide_id=703',
      'https://www.lh-ink.com/photo.php?slide_id=704',
      'https://www.lh-ink.com/photo.php?slide_id=705',
      'https://www.lh-ink.com/photo.php?slide_id=706',
      'https://www.lh-ink.com/photo.php?slide_id=707',
      'https://www.lh-ink.com/photo.php?slide_id=708',
      'https://www.lh-ink.com/photo.php?slide_id=709',
      'https://www.lh-ink.com/photo.php?slide_id=710',
      'https://www.lh-ink.com/photo.php?slide_id=711',
      'https://www.lh-ink.com/photo.php?slide_id=712',
      'https://www.lh-ink.com/photo.php?slide_id=713',
      'https://www.lh-ink.com/photo.php?slide_id=714',
      'https://www.lh-ink.com/photo.php?slide_id=715',
      'https://www.lh-ink.com/photo.php?slide_id=716',
      'https://www.lh-ink.com/photo.php?slide_id=717',
      'https://www.lh-ink.com/photo.php?slide_id=718',
      'https://www.lh-ink.com/photo.php?slide_id=719',
      'https://www.lh-ink.com/photo.php?slide_id=720',
      'https://www.lh-ink.com/photo.php?slide_id=721',
      'https://www.lh-ink.com/photo.php?slide_id=722',
      'https://www.lh-ink.com/photo.php?slide_id=723',
      'https://www.lh-ink.com/photo.php?slide_id=724',
      'https://www.lh-ink.com/photo.php?slide_id=725',
      'https://www.lh-ink.com/photo.php?slide_id=726',
      'https://www.lh-ink.com/photo.php?slide_id=727',
      'https://www.lh-ink.com/photo.php?slide_id=728',
      'https://www.lh-ink.com/photo.php?slide_id=729',
      'https://www.lh-ink.com/photo.php?slide_id=730',
      'https://www.lh-ink.com/photo.php?slide_id=731',
      'https://www.lh-ink.com/photo.php?slide_id=732',
      'https://www.lh-ink.com/photo.php?slide_id=733',
      'https://www.lh-ink.com/photo.php?slide_id=734',
      'https://www.lh-ink.com/photo.php?slide_id=735',
      'https://www.lh-ink.com/photo.php?slide_id=736',
      'https://www.lh-ink.com/photo.php?slide_id=737',
      'https://www.lh-ink.com/photo.php?slide_id=738',
      'https://www.lh-ink.com/photo.php?slide_id=739',
      'https://www.lh-ink.com/photo.php?slide_id=730',
      'https://www.lh-ink.com/photo.php?slide_id=741',
      'https://www.lh-ink.com/photo.php?slide_id=742',
      'https://www.lh-ink.com/photo.php?slide_id=743',
      'https://www.lh-ink.com/photo.php?slide_id=744',
      'https://www.lh-ink.com/photo.php?slide_id=745',
      'https://www.lh-ink.com/photo.php?slide_id=746',
      'https://www.lh-ink.com/photo.php?slide_id=747',
      'https://www.lh-ink.com/photo.php?slide_id=748',
      'https://www.lh-ink.com/photo.php?slide_id=749',
      'https://www.lh-ink.com/photo.php?slide_id=750',
      'https://www.lh-ink.com/photo.php?slide_id=751',
      'https://www.lh-ink.com/photo.php?slide_id=752',
      'https://www.lh-ink.com/photo.php?slide_id=753',
      'https://www.lh-ink.com/photo.php?slide_id=754',
      'https://www.lh-ink.com/photo.php?slide_id=755',
      'https://www.lh-ink.com/photo.php?slide_id=756',
      'https://www.lh-ink.com/photo.php?slide_id=757',
      'https://www.lh-ink.com/photo.php?slide_id=758',
      'https://www.lh-ink.com/photo.php?slide_id=759',
      'https://www.lh-ink.com/photo.php?slide_id=760',
      'https://www.lh-ink.com/photo.php?slide_id=761',
      'https://www.lh-ink.com/photo.php?slide_id=762',
      'https://www.lh-ink.com/photo.php?slide_id=763',
      'https://www.lh-ink.com/photo.php?slide_id=764',
      'https://www.lh-ink.com/photo.php?slide_id=765',
      'https://www.lh-ink.com/photo.php?slide_id=766',
      'https://www.lh-ink.com/photo.php?slide_id=767',
      'https://www.lh-ink.com/photo.php?slide_id=768',
      'https://www.lh-ink.com/photo.php?slide_id=769',
      'https://www.lh-ink.com/photo.php?slide_id=770',
      'https://www.lh-ink.com/photo.php?slide_id=771',
      'https://www.lh-ink.com/photo.php?slide_id=772',
      'https://www.lh-ink.com/photo.php?slide_id=773',
      'https://www.lh-ink.com/photo.php?slide_id=774',
      'https://www.lh-ink.com/photo.php?slide_id=775',
      'https://www.lh-ink.com/photo.php?slide_id=776',
      'https://www.lh-ink.com/photo.php?slide_id=777',
      'https://www.lh-ink.com/photo.php?slide_id=778',
      'https://www.lh-ink.com/photo.php?slide_id=779',
      'https://www.lh-ink.com/photo.php?slide_id=780',
      'https://www.lh-ink.com/photo.php?slide_id=781',
      'https://www.lh-ink.com/photo.php?slide_id=782',
      'https://www.lh-ink.com/photo.php?slide_id=783',
      'https://www.lh-ink.com/photo.php?slide_id=784',
      'https://www.lh-ink.com/photo.php?slide_id=785',
      'https://www.lh-ink.com/photo.php?slide_id=786',
      'https://www.lh-ink.com/photo.php?slide_id=787',
      'https://www.lh-ink.com/photo.php?slide_id=788',
      'https://www.lh-ink.com/photo.php?slide_id=789',
      'https://www.lh-ink.com/photo.php?slide_id=790',
      'https://www.lh-ink.com/photo.php?slide_id=791',
      'https://www.lh-ink.com/photo.php?slide_id=792',
      'https://www.lh-ink.com/photo.php?slide_id=793',
      'https://www.lh-ink.com/photo.php?slide_id=794',
      'https://www.lh-ink.com/photo.php?slide_id=795',
      'https://www.lh-ink.com/photo.php?slide_id=796',
      'https://www.lh-ink.com/photo.php?slide_id=797',
      'https://www.lh-ink.com/photo.php?slide_id=798',
      'https://www.lh-ink.com/photo.php?slide_id=799',
      'https://www.lh-ink.com/photo.php?slide_id=800',
      'https://www.lh-ink.com/photo.php?slide_id=801',
      'https://www.lh-ink.com/photo.php?slide_id=802',
      'https://www.lh-ink.com/photo.php?slide_id=803',
      'https://www.lh-ink.com/photo.php?slide_id=804',
      'https://www.lh-ink.com/photo.php?slide_id=805',
      'https://www.lh-ink.com/photo.php?slide_id=806',
      'https://www.lh-ink.com/photo.php?slide_id=807',
      'https://www.lh-ink.com/photo.php?slide_id=808',
      'https://www.lh-ink.com/photo.php?slide_id=809',
      'https://www.lh-ink.com/photo.php?slide_id=810',
      'https://www.lh-ink.com/photo.php?slide_id=811',
      'https://www.lh-ink.com/photo.php?slide_id=812',
      'https://www.lh-ink.com/photo.php?slide_id=813',
      'https://www.lh-ink.com/photo.php?slide_id=814',
      'https://www.lh-ink.com/photo.php?slide_id=815',
      'https://www.lh-ink.com/photo.php?slide_id=816',
      'https://www.lh-ink.com/photo.php?slide_id=817',
      'https://www.lh-ink.com/photo.php?slide_id=818',
      'https://www.lh-ink.com/photo.php?slide_id=819',
      'https://www.lh-ink.com/photo.php?slide_id=820',
      'https://www.lh-ink.com/photo.php?slide_id=821',
      'https://www.lh-ink.com/photo.php?slide_id=822',
      'https://www.lh-ink.com/photo.php?slide_id=823',
      'https://www.lh-ink.com/photo.php?slide_id=824',
      'https://www.lh-ink.com/photo.php?slide_id=825',
      'https://www.lh-ink.com/photo.php?slide_id=826',
      'https://www.lh-ink.com/photo.php?slide_id=827',
      'https://www.lh-ink.com/photo.php?slide_id=828',
      'https://www.lh-ink.com/photo.php?slide_id=829',
      'https://www.lh-ink.com/photo.php?slide_id=830',
      'https://www.lh-ink.com/photo.php?slide_id=831',
      'https://www.lh-ink.com/photo.php?slide_id=832',
      'https://www.lh-ink.com/photo.php?slide_id=833',
      'https://www.lh-ink.com/photo.php?slide_id=834',
      'https://www.lh-ink.com/photo.php?slide_id=835',
      'https://www.lh-ink.com/photo.php?slide_id=836',
      'https://www.lh-ink.com/photo.php?slide_id=837',
      'https://www.lh-ink.com/photo.php?slide_id=838',
      'https://www.lh-ink.com/photo.php?slide_id=839',
      'https://www.lh-ink.com/photo.php?slide_id=830',
      'https://www.lh-ink.com/photo.php?slide_id=841',
      'https://www.lh-ink.com/photo.php?slide_id=842',
      'https://www.lh-ink.com/photo.php?slide_id=843',
      'https://www.lh-ink.com/photo.php?slide_id=844',
      'https://www.lh-ink.com/photo.php?slide_id=845',
      'https://www.lh-ink.com/photo.php?slide_id=846',
      'https://www.lh-ink.com/photo.php?slide_id=847',
      'https://www.lh-ink.com/photo.php?slide_id=848',
      'https://www.lh-ink.com/photo.php?slide_id=849',
      'https://www.lh-ink.com/photo.php?slide_id=850',
      'https://www.lh-ink.com/photo.php?slide_id=851',
      'https://www.lh-ink.com/photo.php?slide_id=852',
      'https://www.lh-ink.com/photo.php?slide_id=853',
      'https://www.lh-ink.com/photo.php?slide_id=854',
      'https://www.lh-ink.com/photo.php?slide_id=855',
      'https://www.lh-ink.com/photo.php?slide_id=856',
      'https://www.lh-ink.com/photo.php?slide_id=857',
      'https://www.lh-ink.com/photo.php?slide_id=858',
      'https://www.lh-ink.com/photo.php?slide_id=859',
      'https://www.lh-ink.com/photo.php?slide_id=860',
      'https://www.lh-ink.com/photo.php?slide_id=861',
      'https://www.lh-ink.com/photo.php?slide_id=862',
      'https://www.lh-ink.com/photo.php?slide_id=863',
      'https://www.lh-ink.com/photo.php?slide_id=864',
      'https://www.lh-ink.com/photo.php?slide_id=865',
      'https://www.lh-ink.com/photo.php?slide_id=866',
      'https://www.lh-ink.com/photo.php?slide_id=867',
      'https://www.lh-ink.com/photo.php?slide_id=868',
      'https://www.lh-ink.com/photo.php?slide_id=869',
      'https://www.lh-ink.com/photo.php?slide_id=870',
      'https://www.lh-ink.com/photo.php?slide_id=871',
      'https://www.lh-ink.com/photo.php?slide_id=872',
      'https://www.lh-ink.com/photo.php?slide_id=873',
      'https://www.lh-ink.com/photo.php?slide_id=874',
      'https://www.lh-ink.com/photo.php?slide_id=875',
      'https://www.lh-ink.com/photo.php?slide_id=876',
      'https://www.lh-ink.com/photo.php?slide_id=877',
      'https://www.lh-ink.com/photo.php?slide_id=878',
      'https://www.lh-ink.com/photo.php?slide_id=879',
      'https://www.lh-ink.com/photo.php?slide_id=880',
      'https://www.lh-ink.com/photo.php?slide_id=881',
      'https://www.lh-ink.com/photo.php?slide_id=882',
      'https://www.lh-ink.com/photo.php?slide_id=883',
      'https://www.lh-ink.com/photo.php?slide_id=884',
      'https://www.lh-ink.com/photo.php?slide_id=885',
      'https://www.lh-ink.com/photo.php?slide_id=886',
      'https://www.lh-ink.com/photo.php?slide_id=887',
      'https://www.lh-ink.com/photo.php?slide_id=888',
      'https://www.lh-ink.com/photo.php?slide_id=889',
      'https://www.lh-ink.com/photo.php?slide_id=890',
      'https://www.lh-ink.com/photo.php?slide_id=891',
      'https://www.lh-ink.com/photo.php?slide_id=892',
      'https://www.lh-ink.com/photo.php?slide_id=893',
      'https://www.lh-ink.com/photo.php?slide_id=894',
      'https://www.lh-ink.com/photo.php?slide_id=895',
      'https://www.lh-ink.com/photo.php?slide_id=896',
      'https://www.lh-ink.com/photo.php?slide_id=897',
      'https://www.lh-ink.com/photo.php?slide_id=898',
      'https://www.lh-ink.com/photo.php?slide_id=899',
      'https://www.lh-ink.com/photo.php?slide_id=900',
      'https://www.lh-ink.com/photo.php?slide_id=901',
      'https://www.lh-ink.com/photo.php?slide_id=902',
      'https://www.lh-ink.com/photo.php?slide_id=903',
      'https://www.lh-ink.com/photo.php?slide_id=904',
      'https://www.lh-ink.com/photo.php?slide_id=905',
      'https://www.lh-ink.com/photo.php?slide_id=906',
      'https://www.lh-ink.com/photo.php?slide_id=907',
      'https://www.lh-ink.com/photo.php?slide_id=908',
      'https://www.lh-ink.com/photo.php?slide_id=909',
      'https://www.lh-ink.com/photo.php?slide_id=910',
      'https://www.lh-ink.com/photo.php?slide_id=911'
    ]

    urls.each do |url|
      driver.get(url)
      sleep 2 # ページが完全に読み込まれるのを待つ

      parsed_page = Nokogiri::HTML(driver.page_source)

      # 画像を取得
      image_urls = parsed_page.css('.photo-lists img').map { |img| img['src'] }
      image_1 = image_urls[0] ? URI.join(url, image_urls[0]).to_s : nil
      image_2 = image_urls[1] ? URI.join(url, image_urls[1]).to_s : nil
      image_3 = image_urls[2] ? URI.join(url, image_urls[2]).to_s : nil

      # 説明文を取得
      description = parsed_page.css('.photo-text p').text.strip

      # DBに保存
      if image_1 || image_2 || image_3 || description.present?
        Gallery.create!(
          image_1: image_1,
          image_2: image_2,
          image_3: image_3,
          description: description
        )
        puts "✅ データ保存成功: #{url}"
      else
        puts "⚠️ データが取得できませんでした: #{url}"
      end
    end

    driver.quit
  end
end
